title: Sara Marolt
description: Statistical modelling | Seabird Ecology

remote_theme: hydecorp/hydejack
plugins:
  - jekyll-remote-theme

author:
  about: |
  Ecology and Conservation Masters student at Uppsala University
  picture:  /assets/img/profile.jpg

author:
  social:
    email:    saralina2001@gmail.com
    
menu:
  - title: Home
    url: /
  - title: Research
    url: /research/
  - title: Ringing
    url: /ringing/
  - title: CV
    url: /cv/
  - title: Contact
    url: /contact/

# Hydejack settings
accent_color: rgb(0, 88, 80)   # dark teal academic vibe
paginate: 5
paginate_path: "/page:num/"
