title: Sara Marolt
description: Seabird Ecology | Statistical modelling

remote_theme: hydecorp/hydejack
plugins:
  - jekyll-remote-theme

author:
  about: |
    Ecology and Conservation Masters student at Uppsala University
  picture: /assets/img/profile.jpg
  social:
    email: saralina2001@gmail.com

menu:
  - title: Home
    url: /
  - title: Research
    url: /research/
  - title: Ringing
    url: /ringing/
  - title: CV
    url: /cv/

# Hydejack settings
accent_color: rgb(0, 88, 80)
paginate: 5
paginate_path: "/page:num/"
