title: Sara Marolt
description: Statistical modelling | Seabird Ecology

remote_theme: hydecorp/hydejack
plugins:
  - jekyll-remote-theme

author:
  name: Sara Marolt
  avatar: /assets/images/d291dd99-8b77-4ae0-91a8-9e279f401b50.jpg

# Hydejack settings
accent_color: rgb(0, 88, 80)   # dark teal academic vibe
paginate: 5
paginate_path: "/page:num/"
