title: Sara Marolt
description: Statistical modelling | Seabird Ecology

remote_theme: hydecorp/hydejack
plugins:
  - jekyll-remote-theme

include:
  - assets/css/custom.css

author:
  name: Sara Marolt
  avatar: /assets/images/profile.jpg

menu:
  - title: Blog
    url:   /blog/
  - title: Projects
    url:   /projects/
  - title: Resume
    url:   /resume/
  - title: About
    url:   /about/

# Hydejack settings
accent_color: rgb(0, 88, 80)   # dark teal academic vibe
paginate: 5
paginate_path: "/page:num/"
