title: Sara Marolt
description: Statistical modelling | Seabird Ecology

remote_theme: hydecorp/hydejack
plugins:
  - jekyll-remote-theme
  
image:
  path:    /assets/images/profile.jpg
  srcset:
    1920w: /assets/images/profile.jpg
    960w:  /assets/images/profile.,5x.jpg
    480w:  /assets/images/profile.,25x.jpg

menu:
  - title: Home
    url: /
  - title: Research
    url: /research/
  - title: Ringing
    url: /ringing/
  - title: CV
    url: /cv/
  - title: Contact
    url: /contact/

# Hydejack settings
accent_color: rgb(0, 88, 80)   # dark teal academic vibe
paginate: 5
paginate_path: "/page:num/"
